### ISSUE TITLE
grunt build failure

### ISSUE THREAD

**Issue by jgoodall** [paulRbr/generator-webapp-rjs#4]
Installing the generator fresh and running `grunt build` fails:

```
Running "requirejs:dist" (requirejs) task
{ [Error: Error: /private/tmp/webapp/.tmp/scripts/main.js does not exist.
    at /private/tmp/webapp/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:26555:27
]
  originalError: [Error: /private/tmp/webapp/.tmp/scripts/main.js does not exist.] }
```

**Comment by paulRbr** [comment]
Thanks for pointing it out, fixed with  991aa1f767

**Comment by Darksoulsong** [comment]
I wonder if that fix was applied to the repository. I just did a fresh install and I've got the very same issue.

```
Error: Error: /fakepath/app/.tmp/scripts/main.js does not exist.
```

**Comment by jgoodall** [comment]
I just tried this again with the newest version and got the same error.

**Comment by caseprince** [comment]
I was able to fix this in v0.4.8 by modifying the Gruntfile.js. Change line 200 from

<pre><code> baseUrl: '.tmp/scripts',</code></pre>

to

<pre><code> baseUrl: 'app/scripts',</code></pre>

**Comment by chilihead** [comment]
still doesn't work. 
After running `grunt` it fails on jshint (app.js, main.js, test.js do not comply to current jshint configuration). After fixing that it fails because
`>> No "bower" targets found.
Warning: Task "bower" failed. Use --force to continue.`

dist/ doesn't get created at all
